# Generated by Django 5.2.5 on 2025-08-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_user_options_alter_user_managers_and_more'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_company_owner',
            field=models.BooleanField(default=False, verbose_name='Владелец компании'),
        ),
    ]
